set nocompatible                " vim, not vi
filetype off
syntax on
set background=dark
colorscheme candycode
let g:Powerline_symbols = 'fancy'

filetype indent plugin on

set encoding=utf-8
set t_Co=256
set expandtab
set tabstop=2
set cindent
set shiftwidth=4
set number                      " muestra número de lineas
set ruler                       " muestra número de linea en la barra
set more                        " más entrada
set autoread                    " para cambios en el archivo
set nofoldenable                " disable folding
set hlsearch
set showmode
set showcmd
set laststatus=2
set smarttab                    " tab and backspace smart
set tabstop=6                   " 6 espacios
set shiftwidth=6                " 
set showfulltag                 " muestra completado de tags completo
set wildmenu                    " menu has tab completion
set mouse=a                   " soporte para todos los modos
set mousehide                 " oculta mientras se escribe
"set clipboard=unnamed
"set clipboard=unnamedplus

" ----------------------------- Mapeado
nmap <MouseMiddle> <esc>"*p         " pega sin formato el texto
map <F2> :NERDTreeTabsToggle<CR>        " F2 para abrir NERDTreeTabs 
let g:ctrlp_map = '<c-p>' " C-p  para abrir modo normal de CtrlP 
let mapleader = ","

" ------------------------------------
